name: Deploy to ECS

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 257478996314.dkr.ecr.ap-south-1.amazonaws.com

      - name: Build image
        run: |
          docker build -t chat-apps .

      - name: Tag image
        run: |
          docker tag chat-apps:latest \
          257478996314.dkr.ecr.ap-south-1.amazonaws.com/chat-apps:v5

      - name: Push image
        run: |
          docker push \
          257478996314.dkr.ecr.ap-south-1.amazonaws.com/chat-apps:v5

      - name: Force ECS deployment
        run: |
          aws ecs update-service \
            --cluster canopi-dev-ecs \
            --service canopi-dev-ecs \
            --force-new-deployment